@startuml
left to right direction
object "<u>301号室:部屋</u>" as room1 {
    タイプ=シングル
    価格=11000円
    キャンペーン価格=9000円
}
object "<u>302号室:部屋</u>" as room2 {
    タイプ=シングル
    価格=11000円
    キャンペーン価格=9000円
}
object "<u>303号室:部屋</u>" as room3 {
    タイプ=シングル
    価格=11000円
    キャンペーン価格=9000円
}
object "<u>Aさん:利用者</u>" as guest1 {
    
}
object "<u>Bさん:利用者</u>" as guest2 {
    
}
object "<u>ホテルUML:ホテル" as hotel {

}

guest1 -up- hotel
guest2 -up- hotel


room1 -- hotel
room2 -- hotel
room3 -- hotel

guest1 -left- room1
guest2 -left- room3
@enduml