@startuml
left to right direction
object "<u>高橋洋平:重要顧客</u>" as customer1 {

}
object "<u>冷蔵庫:商品</u>" as product1 {
    型式=R8765
}
object "<u>注文情報1:注文</u>" as order1 {
    注文日=11月21日
    注文数=2
}
object "<u>注文情報2:注文" as order2 {
    注文日=11月21日
    注文数=1
}
object "<u>テレビ:商品</u>" as product2 {
    型式=V12345
}

object "<u>髙田理恵:顧客</u>" as customer2 {
    
}
object "<u>注文情報3:注文</u>" as order3 {
    注文日=12月23日
    注文数=1
}

customer1 -- order1
customer1 -- order2
order1 -- product1
order2 -- product2

customer2 -- order3
order3 -- product1


@enduml