@startuml ユースケース図
left to right direction
actor 利用者#DDDDDD;line:black;line.bold;
actor ホテル従業員#DDDDDD;line:black;line.bold;
actor 管理者#DDDDDD;line:black;line.bold;
rectangle ホテル予約システム{
usecase 空席の状況を確認する
usecase (<u>予約する</u>\n拡張点\nキャンペーン期間) as input
usecase 空席の状況を入力する
usecase 予約の集計する
usecase ログインする
usecase 会員登録する
usecase キャンペーン価格にする

}
利用者 --> 空席の状況を確認する
利用者 --> input
input ..> ログインする : << include >>
input <.. キャンペーン価格にする : << extend >>
利用者 --> 会員登録する
ホテル従業員 --> 空席の状況を入力する
空席の状況を入力する ..> ログインする : << include >>
管理者 --> 予約の集計する
予約の集計する ..> ログインする : << include >>
管理者 --|> ホテル従業員

@enduml