@startuml   クラス図
skinparam classAttributeIconSize 0
class 注文  {
    合計
}

class 注文明細 {
    数量
    小計
}

class 割引クーポン {
    値引き額
    期限
}

class 商品 {
    名称
    単価
}

class カップ {
    サイズ
}

class ドリンク {
    種別
}

class レシピ {

}

class フード {

}

class ポテト {
    サイズ
}

class ハンバーガー {
    種別
}

class 材料 {

}

class パン {

}
class 肉 {

}

class 野菜 {
 
}

class チーズ {

}
hide  circle

注文 "1..*" o-right- 注文明細
注文明細 "0..*" -right- "0..1" 割引クーポン
注文明細 "0..*" -- "1" 商品
商品 <|-left- ドリンク
ドリンク "0..*" -left- "1..3" カップ
商品 <|-- フード
フード <|-- ハンバーガー
ハンバーガー "1..*" o-left- "1..*" 材料
材料 <|-- パン
材料 <|-- 肉
材料 <|-- 野菜
材料 <|-- チーズ
フード <|-- ポテト
フード "1" -right- "1" レシピ


@enduml